root = "./"
tmp_dir = "./tmp/"

[build]

pre_cmd = ["echo '@import \"tailwindcss\";' > ./tmp/main.css"]
cmd = "tailwindcss --minify --output ./ui/static/css/tailwind.min.css"
entrypoint = "true"

include_ext = ["templ"]
include_dir = ["./ui/internal/"]

exclude_unchanged = true
delay = 2000
